### ISSUE TITLE
Add a setup.sh to install and check dependencies

### ISSUE THREAD

**Issue by ivanch** [ivanch/channel-downloader#1]
Add a bash script to check dependencies and install them if needed.
* Check if Python version is ok. If not, only alert the user and stop.
* Check if Google Chrome or Chromium is installed. If not, only alert the user.
* Check if Python dependencies are ok. If not, install them with `pip install -r requirements.txt`.
* Check if chromedriver is installed. If not, download the latest and compatible version.

**Comment by cmecklenborg** [comment]
What operating systems would you like to support with this script? Both Mac and Linux?

**Comment by ivanch** [comment]
Hello @cmecklenborg,
Mainly Linux, but Mac is also welcome if it's easy to implement.

**Comment by cmecklenborg** [comment]
Cool, I should have a PR for you in the morning. :)

**Comment by ivanch** [comment]
Thank you, @cmecklenborg!

**Comment by nikhosagala** [comment]
Hey I already submit a PR for this

**Comment by ivanch** [comment]
Issue solved by @nikhosagala with #2
